name: 1-hugo-deploy

on:
  push:
    branches:
    - gh-pages-content

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: hugo.sh
      env:
        GITHUB_SHA: ${{ github.sha }}
        SITE_NAME: 1-hugo
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        cd /home/
        source $GITHUB_WORKSPACE/1-hugo/hugo.sh
        hugo-install-linux
        cd $GITHUB_WORKSPACE/
        hugo-github-deploy

